name: Solar System

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:
    code-coverage:
        runs-on: ubuntu-latest
        steps:
            - run: npm run test
            - run: npm run coverage
              continue-on-error: true
            - uses: actions/upload-artifact@v4
              with: 
                name: coverage reports
                path: coverage/
