name: Solar System

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "MONGO_URI=mongodb://localhost:27017/superData" >> $GITHUB_ENV
          echo "MONGO_USERNAME=anyuser" >> $GITHUB_ENV
          echo "MONGO_PASSWORD=anypassword" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test