name: Solar System

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    env:
      MONGO_URI: 'mongodb://localhost:27017/superData'
      MONGO_USERNAME: anyuser
      MONGO_PASSWORD: anypassword

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test
